// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZVlLt2UgFD_MBOTyXZBRadR5nvJu0FfU',
    appId: '1:671144258512:android:39ba79fe88983b33fa27d5',
    messagingSenderId: '671144258512',
    projectId: 'backfoodloop',
    databaseURL: 'https://backfoodloop-default-rtdb.firebaseio.com',
    storageBucket: 'backfoodloop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh-HTmfq8nbkORdsC3PV0gPELj51cxMzE',
    appId: '1:671144258512:ios:cf06aa6f3090b788fa27d5',
    messagingSenderId: '671144258512',
    projectId: 'backfoodloop',
    databaseURL: 'https://backfoodloop-default-rtdb.firebaseio.com',
    storageBucket: 'backfoodloop.appspot.com',
    androidClientId: '671144258512-jpnap6t1hq9o3rn05nr6lquq56sstvos.apps.googleusercontent.com',
    iosClientId: '671144258512-npkjsns32hm0f8d8hjh0mtk1vjacgmag.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodloop',
  );
}
